/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xe.h"

uint8_t last_button_state = 1; // останній стан кнопки
uint8_t current_mode = 0;      // 0 для 10 Гц, 1 для 25 Гц

void PWM_Init (void);

int main(void)
{
    /*Світлодіод підлючений до PA5 кнопка до PC 13 */
	/*Кнопка має пыдтяжку до 3В на платі*/

	/*Вмикаємо тактування*/
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;


	/*Визначаємо режим роботи*/

	GPIOA->MODER &= ~GPIO_MODER_MODER5;       // Скидання
	GPIOA->MODER &= ~GPIO_MODER_MODER5_0; //PA5 встановлюємо як AF
	GPIOA->MODER |= GPIO_MODER_MODER5_1;

	GPIOC->MODER &= ~GPIO_MODER_MODER13;//PC на вхід


	//ARL від 0 до 8

	// Налаштування PA5 (Low Register: AFR[0]) ---
	GPIOA->AFR[0] &= ~GPIO_AFRL_AFSEL5;           // Очищаємо
	GPIOA->AFR[0] |= (1 << GPIO_AFRL_AFSEL5_Pos); // Встановлюємо AF1 для 5-го піна (PA5)

	PWM_Init();

	while (1) {

		uint8_t current_button_state;

		if (GPIOC->IDR & GPIO_IDR_IDR_13) { // Зчитуємо поточний стан кнопки PC13
			 current_button_state = 1;
		} else{
			current_button_state = 0;
		}

		    //  Перевіряємо, чи кнопка щойно була натиснута
		if (last_button_state == 1 && current_button_state == 0) {

		        // Перемикаємо режим
		        if (current_mode == 0) {
		            TIM2->ARR = 399;  // 25 Гц
		            current_mode = 1;
		        } else {
		            TIM2->ARR = 999;  // 10 Гц
		            current_mode = 0;
		        }

		        // Затримка для антибрязкоту
		        for(volatile int i = 0; i < 500000; i++);
		    }

		    //  Запам'ятовуємо стан для наступної ітерації
		    last_button_state = current_button_state;

		}


}

void PWM_Init (){

	//Нам потрібен таймер 2 для PA5
    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

    // APB1 Timer Clock = 16 MHz.
    // PSC = (16000000 / 10000) - 1 = 1599.
    TIM2->PSC = 1599;

    // Частота 10000 Гц. Для 10 Гц (PWM_freq) ARR = 10000/10 - 1 = 999.
    TIM2->ARR = 999; //10Гц

    TIM2->CCR1 = 100;//10 мс


	// Встановлюємо PWM Mode 1 (110) .
	 TIM2->CCMR1 |= (TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2); // CH1

	/*Вмикаємо канал*/
	 TIM2->CCER |= TIM_CCER_CC1E  ;
	 TIM2->CR1 |= TIM_CR1_CEN;

	 //Зміна частоти тілько коли дорахував цикл
	 TIM2->CR1 |= TIM_CR1_ARPE;


}
